services:
  roscore:
    image: franka_control:latest
    build: 
      context: .
    network_mode: host
    privileged: true
    stdin_open: true # docker run -i
    tty: true # docker run -t
    command: /bin/bash -c '. /catkin_ws/devel/setup.bash && roscore'

  franka_controller:
    env_file: .env
    
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        - VERSION_LIBFRANKA_ARG=${VERSION_LIBFRANKA}

    image: franka_control:latest
    network_mode: host
    privileged: true
    stdin_open: true # docker run -i
    tty: true # docker run -t
    depends_on:
      - roscore
    command: /bin/bash -c '. /catkin_ws/devel/setup.bash && roslaunch --wait serl_franka_controllers impedance.launch robot_ip:=169.254.67.230 load_gripper:=true'

  reset:
    image: franka_control:latest
    build: .
    # environment:
    #   - DISPLAY=${DISPLAY}
    volumes:
      # - /tmp/.X11-unix:/tmp/.X11-unix
      - .:/catkin_ws/src/franka_control
      # - /mnt/afs/grasp-sim:/mnt/afs/grasp-sim
    network_mode: host
    privileged: true
    stdin_open: true # docker run -i
    tty: true # docker run -t
    # depends_on:
      # - roscore
      # - franka_controller
      # - rviz
    working_dir: /catkin_ws/src/franka_control
    # TODO: this doesn't work with '--help' as argument
    entrypoint: /catkin_ws/src/franka_control/reset.sh

  rviz:
    image: franka_control:latest
    build: 
      context: .
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /dev/dri:/dev/dri
      - .:/catkin_ws/src/franka_control
    network_mode: host
    privileged: true
    stdin_open: true # docker run -i
    tty: true # docker run -t
    depends_on:
      - roscore
      - franka_controller
    command: /bin/bash -c '. /catkin_ws/devel/setup.bash && rviz -d /catkin_ws/src/franka_control/res/rviz_config.rviz'

  main:
    image: franka_control:latest
    build: .
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - .:/catkin_ws/src/franka_control
      # - /mnt/afs/grasp-sim:/mnt/afs/grasp-sim
    network_mode: host
    privileged: true
    stdin_open: true # docker run -i
    tty: true # docker run -t
    depends_on:
      # - roscore
      # - franka_controller
      - rviz
    working_dir: /catkin_ws/src/franka_control
    # TODO: this doesn't work with '--help' as argument
    entrypoint: /catkin_ws/src/franka_control/entrypoint.sh



  gripper:
    image: franka_control:latest
    build: .
    network_mode: host
    privileged: true
    stdin_open: true # docker run -i
    tty: true # docker run -t
    depends_on:
      # - roscore
      - franka_controller
      # - rviz
    working_dir: /catkin_ws/src/franka_control
    # TODO: this doesn't work with '--help' as argument
    entrypoint: /catkin_ws/src/franka_control/gripper.sh

