version: '3'

services:
  dev:
    build: 
      context: ..
      dockerfile: Dockerfile
      args:
        - VERSION_LIBFRANKA_ARG=${VERSION_LIBFRANKA:-0.9.2}
    image: franka_control:latest
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /dev/dri:/dev/dri
      - ..:/catkin_ws/src/franka_control
    network_mode: host
    privileged: true
    stdin_open: true
    tty: true
    working_dir: /catkin_ws/src/franka_control
    command: /bin/bash
    user: root
    # Keep the container running
    stop_signal: SIGKILL 